version: "3.8"

networks:
  web-network:
    name: web-network
  gv-network:
    driver: bridge

services:
  db:
    container_name: db
    image: mariadb:11.3
    ports:
      - "3306:3306"
    networks:
      - gv-network
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - banco:/var/lib/mysql
  web:
      container_name: web
      build: .
      networks:
        - web-network
        - gv-network
      ports:
        - "8084:8084"
      env_file:
        - .env
      depends_on:
        - db
  redis:
    container_name: redis
    image: redis:6.2
    networks:
        - gv-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    container_name: minio
    image: minio/minio:latest
    networks:
      - gv-network
      - web-network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped 
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - gv-network
      - web-network