version: "3.8"

networks:
  gv-network:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
  banco:
  redis_data:


services:
  web:
    container_name: web
    build: .
    ports:
        - "8084:8084"
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb:11.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: production
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    volumes:
      - banco:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - gv-network