global:
  scrape_interval: 6s

scrape_configs:
  - job_name: 'production-review'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "web:8084" ]
        labels:
          application: "production-review"